name: 3D Profile Contribution

on:
  schedule:
    - cron: "0 0 * * *" # se actualiza automaticamente una vez al dia
  workflow_dispatch: # permite ejecutarlo manualmente desde la pestaña Actions

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          username: martin-contreras-tech
      - name: Make background transparent
        run: |
          sed -i 's/\.fill-bg { fill: #[0-9a-fA-F]*; }/.fill-bg { fill: none; }/' profile-3d-contrib/*.svg
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A
          git commit -m "generate 3d contribution svg (transparent background)" || exit 0
          git push
